# Generated by Django 3.0.8 on 2020-07-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.FileField(upload_to='productImages/')),
                ('description', models.TextField()),
                ('product_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop')], default='Mobile', max_length=15)),
                ('processor', models.TextField()),
                ('RAM', models.TextField()),
                ('screen_size', models.TextField()),
                ('color', models.TextField()),
                ('hd_capacity', models.TextField()),
            ],
        ),
    ]
